### PR TITLE
Browsable doc

### LINKED ISSUE #50: Browsable documentation
The code documentation should be browsable. Maybe we can use pydoc.

### PR DESCRIPTION
**Pull request by ffsinger**
Closes #50

### CODE REVIEW

**Comment by btellstrom** [comment]
From where is this doc supposed to be read? In a browser?

**Comment by ffsinger** [comment]
Yes, you can simply open doc/src/index.html in a browser and navigate from there. Alternatively, you can open any file directly (e.g. doc/src/main/app.html)

**Comment by btellstrom** [comment]
Okay. Personally I would have preferred a pdf or other directly browsable kind of file, but I guess that's what pydoc generates. Looks good.

**Comment by ffsinger** [comment]
Note that I used **pdoc**, which is a bit more rich than **pydoc**
But for the next project we can of course try to find a tool that produces a pdf. I don't remember having seen this feature when I compared the tools though.

**Comment by btellstrom** [comment]
Okay. Think it might just be me being slightly "eccentric", javadoc writes a html file as well if I remember correctly.

**Pull request merged**
