### PR TITLE
History changes

### LINKED ISSUE #10: Feat: Ability to connect and add documents to database
We need the ability to connect to the database and insert documents following the [schema](https://github.com/btellstrom/DD2480_group_19_CI/doc/mongo/build-schema.json).

### PR DESCRIPTION
**Pull request by btellstrom**
Closes #10

### CODE REVIEW

**Comment by btellstrom** [comment]
When I resent the package, the webhook properly received the webhook. Not sure why it claims it fails...

**Comment by btellstrom** [comment]
Ahh... Ali changed the default value in `ci.ini` which makes a test fail. Probably poor practice by me to have the test rely on the actual config-file.

**Comment by A1337li** [comment]
Oh sorry about that. I should have ran the tests

**Comment by btellstrom** [comment]
Nah, bad practice by me to have a test rely on something that is supposed to be changed.

**Review by A1337li — APPROVED** [review]
Everything looks fine

**Pull request merged**
